name: Poll Counter-Strike Updates
run-name: Poll Counter-Strike Updates 🚀

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 16 * * *'

jobs:
  crawl-latest-csgo-update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements-workflow.txt
      - run: python update.py
      - run: |
          git add --all images/
          if git diff --quiet; then
            exit 0
          fi
          git config --global user.name 'Christoph Kreisl'
          git config --global user.email ${{ secrets.EMAIL_ADDRESS }}
          git commit --all --message='Auto update data'
          git push
